name: Node.js CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Set up Node.js (specify the version you're using)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or '14', depending on which version you're using
    
    # Install dependencies
    - name: Install dependencies
      run: npm install
    
    # Compile TypeScript files
    - name: Compile TypeScript
      run: npx tsc  # This will compile your TypeScript files to JavaScript
    
    # Run the tests
    - name: Run tests
      run: npm test
